Display correct size values
0chain/gosdk pull request #1033
Opened 2023-06-12 14:44 UTC by din-mukhammed

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test: https://github.com/0chain/system_test/pull/726
- zboxcli: https://github.com/0chain/zboxcli/pull/456/
- zwalletcli:
- Other: ...

2023-06-16 11:59 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-16 14:34 UTC, Kishan-Dhakan requested changes

2023-06-16 14:34 UTC, Kishan-Dhakan commented on zboxcore/sdk/allocation.go
> +	return a.DataShards + a.ParityShards, a.DataShards
What's the reason for this change?
Minimum Data+1 number of shards are required to recover the full data as far as I remember. @lpoli please review this change.

2023-06-17 01:07 UTC, din-mukhammed commented on zboxcore/sdk/allocation.go
> +	return a.DataShards + a.ParityShards, a.DataShards
I think consensus threshold (as in minimum number of shards needed to reconstruct the original data) should be equal to number of data shards, I don't quite understand why we use "data+1".

2023-06-19 12:21 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-23 18:24 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-01 14:10 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-june-5  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-03 15:39 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-04 10:02 UTC, dabasov reviewed
lgtm

2023-07-07 13:38 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-07 15:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-08 23:00 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-09 09:19 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | 1033-fix-list  |
| gosdk  | fix/get-list-from-blobbers  |
| zboxcli  | display-correct-sizes  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | sprint-july-1  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-09 16:28 UTC, merged