Multi download operation in mobilesdk
0chain/gosdk pull request #1045
Opened 2023-06-16 04:55 UTC by Hitenjain14

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-06-22 10:47 UTC, boddumanohar commented
@Hitenjain14  please also replace the current [current download method in wasm demo](https://github.com/0chain/gosdk/blob/1df91bf714ae22957348a532998263519585ecda/wasmsdk/demo/index.html#L470) with multiDownload

2023-07-01 18:27 UTC, dabasov requested changes

2023-07-01 18:27 UTC, dabasov commented on mobilesdk/zbox/storage.go
> +	if options[len(options)-1].DownloadOp == 1 {
can there be 0 options? please add a check

2023-07-01 18:27 UTC, dabasov commented on zboxcore/sdk/read_counter_ctr.go
> +	mut := brc.blobberLockMap[key]
check if nothing is found din the map

2023-07-01 18:27 UTC, dabasov commented on zboxcore/sdk/allocation.go
> -			err := sem.Acquire(ctx, 1)
why do we create goroutines without any control?

2023-07-03 08:30 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | feature/mutli-download  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | sprint-july-1  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-04 10:04 UTC, dabasov approved these changes
lgtm

2023-07-04 10:05 UTC, merged