added caching instead of the network call to estimate the transaction fees
0chain/gosdk pull request #1056
Opened 2023-06-20 20:50 UTC by SrLeet03

### Changes
- Implement caching to avoid network calls for retrieving values.

### Fixes
- None  

### Details
- Create a cache object with a capacity of 100 to store the retrieved values.
- Check if the value exists in the cache before making a network call.
- If the value is found in the cache, retrieve it from the cache and return it.
- If the value is not found in the cache, make a network call to fetch it and store it in the cache for future use.
- Update the relevant code sections to utilise the caching mechanism.
                  
This PR improves performance by reducing network calls and improving response times for subsequent requests.

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-06-24 13:25 UTC, dabasov requested changes

2023-06-24 13:25 UTC, dabasov commented on core/transaction/entity.go
> +func GetFeesFromCache() {
what is it for?

2023-06-24 13:25 UTC, dabasov commented on sdkversion
remove this

2023-06-24 13:25 UTC, dabasov commented on sdkversion.go
what is it for?

2023-06-25 07:48 UTC, SrLeet03 commented on core/transaction/entity.go
> +func GetFeesFromCache() {
sure, will remove that

2023-06-25 08:50 UTC, SrLeet03 commented
Also, @dabasov, could you help point out where I should put this initLRUCache function?

2023-06-25 08:51 UTC, SrLeet03 commented on sdkversion.go
At the time of local setup of gosdk @boddumanohar asked me the same, sorry forgot to remove it before pushing .

2023-06-25 19:43 UTC, dabasov approved these changes
lgtm

2023-06-26 04:07 UTC, cnlangzi requested changes
It doesn't work properly in zbox/zwallet and wasm.
- re zbox/zwallet, one command is one instance. it can't read cache from previous instance
- re wasm, one session is one instance. it can't read cache from other session/instance. 

I think it is better to add persistent storage support
- re zbox/zwallet, it should be cached to ~/.zcn/fees.cache
- re wasm, it should be cached to localStorage

2023-06-27 16:48 UTC, dabasov commented on core/transaction/entity.go
> +func initLRUCache() {
use once and package level function `init()`, check how it is done for nonceCache

2023-06-29 15:16 UTC, closed without merging