fix caching for fees table
0chain/gosdk pull request #1113
Opened 2023-07-13 20:57 UTC by boddumanohar

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-07-14 13:24 UTC, dabasov requested changes

2023-07-14 13:24 UTC, dabasov commented on core/transaction/entity.go
> +	json.Unmarshal([]byte(txData), &sn)
please handle the error

2023-07-16 20:36 UTC, boddumanohar commented on core/transaction/entity.go
> +	json.Unmarshal([]byte(txData), &sn)
fixed in 38b9f59

2023-07-20 17:49 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | fix-fees  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-07-22 09:20 UTC, merged

2023-07-22 09:21 UTC, dabasov reviewed
lgtm