Fix upload consensus
0chain/gosdk pull request #1176
Opened 2023-08-19 10:10 UTC by Hitenjain14

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-08-19 17:57 UTC, din-mukhammed approved these changes
LGTM

2023-08-19 19:44 UTC, dabasov requested changes

2023-08-19 19:44 UTC, dabasov commented on zboxcore/sdk/allocation.go
> +		numBlocks, verifyDownload, status, "", localFilePath)
why do we set connectionID after?

2023-08-19 19:44 UTC, dabasov commented on zboxcore/sdk/chunked_upload.go
> +					wgErrors <- err
goroutines can get stuck here, as only one message will be read from wgErrors

2023-08-19 20:01 UTC, dabasov approved these changes
lgtm

2023-08-21 13:52 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | hotfix/upload-consensus  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-08-22 07:53 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | hotfix/upload-consensus  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  |   |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-08-22 15:22 UTC, merged