[WIP] [Feature] Allocation by blobber
0chain/gosdk pull request #124
Opened 2021-06-23 16:44 UTC by moldis

This branch should be merged after ETH wallet features.

1. It's adding the possibility to get the cost of storage for listed blobbers only
2. Create allocation for listed blobbers only

All these features are mandatory for mobile clients

2021-08-03 07:16 UTC, moldis commented
@NoSkillGuy Pls confirm or leave comments here, otherwise I will merge it as need this feature for Android/IOS

2021-08-04 15:25 UTC, cnlangzi requested changes

2021-08-04 15:25 UTC, cnlangzi commented on zboxcore/sdk/allocation.go
> +	blobbersCopy := blobbers
why we need a `blobbersCopy`?

2021-08-04 15:25 UTC, cnlangzi commented on zboxcore/sdk/allocation.go
> +		fmt.Printf("write price for blobber %f datashards %d parity %d\n",
please don't use fmt.Printf to print log. It is impossible to turn off in config file.

2021-08-05 08:13 UTC, cnlangzi approved these changes
LGTM

2021-08-05 08:14 UTC, merged