split-key handlers implementation in wasm
0chain/gosdk pull request #1255
Opened 2023-10-14 19:59 UTC by Ash-KODES

### Changes
-Added methods of Split key in wasm required for web flow implementation in bolt web app.

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

2023-10-16 03:20 UTC, peterlimg requested changes, later dismissed

2023-10-16 03:20 UTC, peterlimg commented on wasmsdk/wallet_base.go
> +var _config localConfig
The `_config` is defined in zcncore package, what we need to do is just call the `SplitKeys` and `SetWalletInfo`.

2023-10-16 03:20 UTC, peterlimg commented on wasmsdk/wallet_base.go
> +	StatusUnknown          int = -1
Let's use them via `zcncore` package instead of re-define them here.

2023-10-16 03:20 UTC, peterlimg commented on wasmsdk/wallet_base.go
> +	return wStr, nil
call `zcncore.SplitKeys(privateKey, numSplits)`

2023-10-16 03:20 UTC, peterlimg commented on wasmsdk/wallet_base.go
> +	return err
Call `zcncore.SetWalletInfo()`

2023-10-16 03:20 UTC, peterlimg commented on wasmsdk/wallet_base.go
> +	return nil
Call `zcncore.SetAuthUrl()`

2023-10-16 03:20 UTC, peterlimg commented on wasmsdk/transaction_base.go
> +type localConfig struct {
not needed as they are in `zcncore` package

2023-10-16 03:20 UTC, peterlimg commented on wasmsdk/transaction_base.go
> +type ChainConfig struct {
Same as above

2023-10-17 20:51 UTC, dabasov approved these changes
lgtm

2023-10-18 16:29 UTC, merged