Repair size
0chain/gosdk pull request #1529
Opened 2024-06-14 08:27 UTC by storybehind

### Changes
- Gets the size in bytes to repair allocation
- Sample json structure:

```
{
    "upload_size" : 1024,
    "download_size": 2048
}
```

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2024-06-18 13:45 UTC, Hitenjain14 requested changes

2024-06-18 13:45 UTC, Hitenjain14 commented on zboxcore/sdk/repairworker.go
> +					rs.UploadSize += uint64(repairOp.Mask.CountOnes()) * uint64(getShardSize(repairOp.FileMeta.ActualSize, r.allocation.DataShards, dir.EncryptionKey != ""))
The dir object won't have encrypted key, the file object will have it. You can add a private field to operation request and set if the file is encrypted.

2024-06-18 14:34 UTC, storybehind commented on zboxcore/sdk/repairworker.go
> +					rs.UploadSize += uint64(repairOp.Mask.CountOnes()) * uint64(getShardSize(repairOp.FileMeta.ActualSize, r.allocation.DataShards, dir.EncryptionKey != ""))
addressed

2024-06-18 14:41 UTC, Hitenjain14 approved these changes
lgtm

2024-06-21 15:29 UTC, dabasov approved these changes
lgtm

2024-06-21 15:29 UTC, merged