re-implemented `CreateDir` and added development client toolkit
0chain/gosdk pull request #267
Opened 2021-10-19 02:34 UTC by cnlangzi

- Added new development client toolkit. see [detail](https://github.com/0chain/gosdk/blob/676f424e3ba61d9f33a61de36c48bc68dab10344/sdks/blobber/blobber.go#L34). It helps us to focus on request and response body without taking too much time on http 
- Re-implemented `CreateDir` feature on sdks
- Forwarded old `CreateDir`

linked to https://github.com/0chain/blobber/pull/395

2021-10-21 14:22 UTC, lpoli commented on zboxcore/sdk/dir_create.go
> +func CreateDir(ctx context.Context, allocationID string, name string) error {
I suppose this should a method of an allocation object just like other functions like; copy, move, list, etc

2021-10-21 14:27 UTC, lpoli commented on zboxcore/sdk/allocation.go
> +// CreateDir [Deprecated]please use sdks.CreateDir
why deprecated?

2021-10-22 01:28 UTC, cnlangzi commented on zboxcore/sdk/dir_create.go
> +func CreateDir(ctx context.Context, allocationID string, name string) error {
hmm, good question. it should be a personal favor.

- I like to make consumer easy to use sdk method. In zboxcli, it is easy to pass inputs to sdks.CreateDir without too much other jobs.
```
// use dir-create instead
var createDirCmd = &cobra.Command{
	Use:        "createdir",
	Deprecated: "please use mkdir",
	Short:      "Create directory in allocation",
	Long:       `Create directory in allocation`,
	Args:       cobra.MinimumNArgs(0),
	Run: func(cmd *cobra.Command, args []string) {
		fflags := cmd.Flags()              // fflags is a *flag.FlagSet
		if !fflags.Changed("allocation") { // check if the flag "path" is set
			PrintError("Error: allocation flag is missing") // If not, we'll let the user know
			os.Exit(1)                                      // and return
		}
		if !fflags.Changed("dirname") {
			PrintError("Error: dirname flag is missing")
			os.Exit(1)
		}

		allocationID := cmd.Flag("allocation").Value.String()
		dirname := cmd.Flag("dirname").Value.String()

		err := sdk.CreateDir(context.TODO(), allocationID, dirname)

		if err != nil {
			PrintError("ERR: ", err.Error())
			return
		}

		PrintInfof("OK: created directory '%s'", dirNewName)
	},
}

var dirNewCmd = &cobra.Command{
	Use:   "dir-new",
	Short: "Create directories named on blobbers",
	Long:  `Create directories named on blobbers`,
	Run: func(cmd *cobra.Command, args []string) {
		err := sdk.CreateDir(context.TODO(), dirNewAllocationID, dirNewName)

		if err != nil {
			PrintError("ERR: ", err.Error())
			return
		}

		PrintInfof("OK: created directory '%s'", dirNewName)
	},
}
  ```
- I don't like too much OOP in golang. Because golang is not design for OOP. I am trying refactor whole sdks one by one in `sdks` package.

2021-10-22 01:28 UTC, cnlangzi commented on zboxcore/sdk/allocation.go
> +// CreateDir [Deprecated]please use sdks.CreateDir
because it is forwarded.

2021-10-22 04:53 UTC, moldis commented on sdks/blobber/blobber.go
> +func (b *Blobber) CreateDir(allocationID, name string) error {
@cnlangzi I think it should remain in the allocation object, just like other operations with files. More more we don't have access on clients to blobber object, so moving it here will broke all current implementation

2021-10-22 04:54 UTC, moldis commented on sdks/zbox.go
> +func (z *ZBox) DoPost(req *Request, handle resty.Handle) *resty.Resty {
zboxsdk already has lot's of methods for POST's why does it reimplemented here?

2021-10-22 04:55 UTC, moldis commented on sdks/blobber/blobber.go
> +func (b *Blobber) CreateDir(allocationID, name string) error {
+ clients have no idea what blobber is, all of them operating with allocation objects

2021-10-22 05:01 UTC, moldis commented on zboxcore/sdk/dir_create.go
> +func CreateDir(ctx context.Context, allocationID string, name string) error {
@cnlangzi I prefer to keep in allocation object. Bcz clients have no idea about blobber objects

2021-10-22 05:02 UTC, moldis commented on zboxcore/fileref/fileref.go
> +		//return r.Hash
That's risky. Please test your approach with share directory function.

2021-10-22 05:03 UTC, moldis commented on sdks/zbox.go
> +func (z *ZBox) DoPost(req *Request, handle resty.Handle) *resty.Resty {
zboxutil.HttpDo

2021-10-22 05:04 UTC, moldis commented on sdks/blobber/vars.go
> +	EndpointDirNew = "/v1/dir/%s"
Why was this move alone from all other related methods with files?

2021-10-22 05:05 UTC, moldis commented on sdks/blobber/blobber.go
> +	errs := r.Wait()
This call mostly will block the main thread on clients and cause ANR, previously we had a WaitGroup to avoid such issues.

2021-10-22 05:09 UTC, moldis requested changes
Need some clarification

2021-10-22 07:28 UTC, lpoli commented on zboxcore/sdk/dir_create.go
> +func CreateDir(ctx context.Context, allocationID string, name string) error {
There is one issue with your approach. You are thinking it in terms of command operations. 0fs and 0s3-server uses allocation object to do most operations. 
These two projects makes a single request for getting an allocation object and using that object it will do other file operations. 
With your approach, for each file operation, a request for an allocation object is required. 

Also this kind of changes will affect all the repo. So `gosdk` and `blobber` changes should be made only after discussion with other members.

Optimization is not a problem, its always good to have. But for structural changes, many things have to considered.

2021-10-22 07:30 UTC, lpoli commented on sdks/blobber/blobber.go
> +func (b *Blobber) CreateDir(allocationID, name string) error {
It is breaking 0s3, 0s3-server, 0fs, 0ipfs, etc.

2021-10-22 08:59 UTC, lpoli commented on core/resty/vars.go
> +	DefaultRequestTimeout = 0 * time.Second
request timeout set to 0?

2021-10-22 09:12 UTC, lpoli commented on dev/blobber/init.go
>  }
Is this `dev` directory for development purpose only?

2021-10-23 14:04 UTC, Sriep commented on zboxcore/sdk/dir_create.go
> +func CreateDir(ctx context.Context, allocationID string, name string) error {
I prefer to keep CreateDir in the allocation object, changes to existing interface objects should be kept to a minimum.

2021-10-23 14:29 UTC, guruhubb commented on zboxcore/sdk/dir_create.go
> +func CreateDir(ctx context.Context, allocationID string, name string) error {
I agree. We're sprinting towards mainnet and should minimize disruption and optimization at this late stage. We have other higher priority issues.

2021-12-27 08:39 UTC, closed without merging