feat: get wasm sdk worked with js-client-sdk and block-explorer
0chain/gosdk pull request #309
Opened 2021-12-01 12:11 UTC by cnlangzi

2021-12-02 13:15 UTC, Rizary commented on core/zcncrypto/helper.go
> +	p.SetHexString("1 " + n2 + " " + n1 + " " + n4 + " " + n3) //nolint
I don't think we need the `MiraclToHerumiPK` function after this PR, no?

2021-12-02 13:19 UTC, Rizary commented on wasmsdk/jsbridge/input.go
> +	if jv.Truthy() {
`Truthy` didn't cover if js.Value is type of Array specifically. Hence, we need to call `isArray` function to be precised.

2021-12-02 13:20 UTC, Rizary commented on wasmsdk/jsbridge/input_test.go
>  package jsbridge
need to add more test in the TestBinder for javascript array

2021-12-02 13:22 UTC, Rizary requested changes
We still need to think custom type for the binder.

But if you want to do it in separate PR, that's fine for me.

2021-12-02 23:21 UTC, cnlangzi commented
> We still need to think custom type for the binder.
> 
> But if you want to do it in separate PR, that's fine for me.

Yes. new custom binder will be added if it necessary in the future. for now. it works enough for our wasm sdk

2021-12-04 02:25 UTC, Rizary approved these changes
lgtm

2021-12-06 13:39 UTC, merged