#111/resume upload
0chain/gosdk pull request #33
Opened 2021-05-10 13:32 UTC by cnlangzi

Added chunk upload feature in Upload/Update

- refactor prepareUpload , and move them into UploadManager
- remember upload progress. it will be resumed to upload instead of from scratch when the UploadRequest raised again. 

*stream feature* is not implemented yet. so it still has a memory performance issue.

2021-05-11 10:33 UTC, Sriep commented on zboxcore/sdk/uploadworker.go
Can we have unit tests for these new  `uploadManager` methods.

2021-05-11 10:36 UTC, Sriep commented
If possible could there be parallel unit tests, to check that the [uploadManagersMutex](https://github.com/0chain/gosdk/blob/9905cf29926e9dcf6dedca1bece77ac14d4e182c/zboxcore/sdk/upload_manager.go#L25) is doing its job of preventing concurrent access?

2021-05-11 14:22 UTC, moldis commented on zboxcore/sdk/upload_manager.go
> +	hWr := io.MultiWriter(h)
@cnlangzi Could add proper variables naming please

2021-05-11 14:59 UTC, moldis commented on zboxcore/sdk/upload_manager.go
> +		h1 := sha1.New()
+1 for proper variable names

2021-05-11 15:05 UTC, moldis commented on zboxcore/sdk/upload_manager.go
> +		hWr1.Write(fileBytes)
Logic not really clear for me, how this variable works `hWr1`

2021-05-12 22:21 UTC, cnlangzi commented on zboxcore/sdk/upload_manager.go
> +func (um *UploadManager) Load(req *UploadRequest, a *Allocation, file *fileref.FileRef, uploadCh chan []byte, uploadThumbCh chan []byte) {
Yes. It is a problem from old code. Almost of code of old gosdk need to be updated. Because the file is full-loaded in memory more than one times.

2021-05-12 22:22 UTC, cnlangzi commented on zboxcore/sdk/upload_manager.go
> +	hWr := io.MultiWriter(h)
OK

2021-05-12 22:59 UTC, cnlangzi commented on zboxcore/sdk/upload_manager.go
> +func (um *UploadManager) Load(req *UploadRequest, a *Allocation, file *fileref.FileRef, uploadCh chan []byte, uploadThumbCh chan []byte) {
leave it with me first.

2021-05-14 08:03 UTC, moldis commented on zboxcore/sdk/upload_manager.go
> +func (um *UploadManager) Load(req *UploadRequest, a *Allocation, file *fileref.FileRef, uploadCh chan []byte, uploadThumbCh chan []byte) {
Yes, I think it has to be in a single loop.

2021-05-14 08:10 UTC, moldis commented on zboxcore/sdk/upload_manager.go
> +		if len(thumbnailBytes) > 0 {
@cnlangzi I can't find a place where it's checking from what place file should start the upload (If it's a break in the middle)

2021-05-14 08:10 UTC, moldis requested changes
Need changes in logic

2021-05-27 06:41 UTC, cnlangzi commented
A new PR will be submitted. close first.

2021-05-27 06:41 UTC, closed without merging