Adapting gosdk to zbomobile
0chain/gosdk pull request #364
Opened 2022-01-27 03:46 UTC by moldis

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
...

2022-02-10 07:52 UTC, cnlangzi requested changes

2022-02-10 07:52 UTC, cnlangzi commented on core/common/fs_mem_mobile.go
> +type MemFS struct {
fs_mem.go doesn't work for mobile?

2022-02-10 07:52 UTC, cnlangzi commented on core/common/fs_mobile.go
> +type FS interface {
it seems be same as fs.go completely? is it possible to reuse it instead of duplicated one?

2022-04-12 03:14 UTC, moldis commented
Not required as fixed in gomobile repo

2022-04-12 03:14 UTC, closed without merging