Add public share to blobber
0chain/gosdk pull request #367
Opened 2022-02-05 06:38 UTC by lpoli

This PR contains following changes:
1. Simply authticket generation to single function
2. Add public share to blobber. Previous public share was unrevokable.
3. Reduce conversions.

2022-02-05 06:50 UTC, Kishan-Dhakan requested changes, later dismissed

2022-02-05 06:50 UTC, Kishan-Dhakan commented on zboxcore/sdk/allocation.go
> +	// return authTicket, nil
Please remove commented code before merge (here + below)

2022-02-06 03:02 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/public-share-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-06 05:35 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | fix/public-share-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-08 18:32 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/public-share-issue  |
| gosdk  | fix/public-share-issue  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-09 04:58 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | fix/public-share-issue  |
| zboxcli  | fix/public-share-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-09 13:43 UTC, dabasov approved these changes
lgtm

2022-02-09 14:02 UTC, cnlangzi requested changes, later dismissed
@lpoli  we need get system-test passed first.

2022-02-10 01:19 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | fix/public-share-issue  |
| zboxcli  | fix/public-share-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-10 01:43 UTC, merged