remove pay interest
0chain/gosdk pull request #368
Opened 2022-02-06 12:22 UTC by Sriep

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
...

Pay reward request for https://github.com/0chain/0chain/pull/967.

2022-02-09 17:39 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | sp_gosdk_rewards  |
| zboxcli  | sp_reward  |
| zwalletcli  | staging  |
| 0chain  | sp-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-10 18:03 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | sp_gosdk_rewards  |
| zboxcli  | sp_reward  |
| zwalletcli  | staging  |
| 0chain  | sp-rewards  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-13 03:20 UTC, peterlimg commented on zcncore/transaction.go
> +	go func() { t.submitTxn() }()
I would prefer go t.submitTxn() unless there are more works need to do in the goroutine.

2022-02-13 03:21 UTC, peterlimg commented on zcncore/transactionauth.go
> +	go func() { ta.submitTxn() }()
go ta.submitTxn()

2022-02-13 03:46 UTC, peterlimg requested changes

2022-02-13 03:46 UTC, peterlimg commented on zboxcore/sdk/sdk.go
> +func CollectRewards(poolId string, providerType int) (string, error) {
Use Provider for providerType explicitly so that the sdk user can be reminded to use the Provider type from sdk instead of define it themselves.

2022-02-13 03:46 UTC, peterlimg commented on zcncore/transaction.go
> +	go func() { t.submitTxn() }()
I would prefer go t.submitTxn() unless there are more works need to do in the goroutine.

2022-02-13 03:46 UTC, peterlimg commented on zcncore/transactionauth.go
> +	go func() { ta.submitTxn() }()
Prefer go ta.submitTxn()

2022-02-15 04:39 UTC, peterlimg approved these changes
LGTM

2022-02-19 17:09 UTC, merged