Return actual file size file info in RemoteFileList
0chain/gosdk pull request #40
Opened 2021-05-14 04:12 UTC by iamrz1

Upload files to dStorage using io reader (from local or remote locations). It helps to compare file sizes and make an informed decision.

2021-05-15 10:43 UTC, moldis commented on zboxcore/sdk/sync.go
>  type fileInfo struct {
Actual Size is already added to fileRef
https://github.com/0chain/gosdk/commit/a7eeb212ef107e889f80bdf90c274b9c8f41019f

2021-05-15 10:44 UTC, moldis requested changes
Please, check my comments, not sure if this branch needed

2021-05-15 10:50 UTC, iamrz1 commented
Okay, that will do.

2021-05-15 11:56 UTC, iamrz1 commented
I guess there are a few structs that returns fileInfo, this one is in sync.go. this struct is used in GetAllocation(). So I think we need this pr.

2021-05-22 15:23 UTC, Sriep requested changes
Three files with no real changes, need to be reverted. Only `sync.go` belongs in this PR.

Adding a field looks harmless, but I can't find anywhere it is used. Is there a link to it being used? Or is there a follow-up PR that will make use of the field?

2021-05-22 15:23 UTC, Sriep commented on core/zcncrypto/bls0chain_test.go
> +	TestSignatureScheme(t)
No meaningful changes here, revert changes to this file.

2021-05-22 15:23 UTC, Sriep commented on zboxcore/sdk/allocation_test.go
> +		require.Equal(t, 0.01, maxR)
No meaningful changes here, revert changes to this file.

2021-05-22 15:23 UTC, Sriep commented on core/zcncrypto/zcncrypto.go
> +
No meaningful changes here, revert changes to this file.

2021-05-27 15:53 UTC, iamrz1 commented
> Three files with no real changes, need to be reverted. Only `sync.go` belongs in this PR.
> 
> Adding a field looks harmless, but I can't find anywhere it is used. Is there a link to it being used? Or is there a follow-up PR that will make use of the field?

I removed the other fmt related changes.
There's a PR in zbox-cli (https://github.com/0chain/zboxcli/pull/21) that uses actual file size to compare existing file (in dStorage) with source file to determine if that upload was complete.

2021-05-31 14:26 UTC, Sriep approved these changes

2021-05-31 14:28 UTC, merged