partial delete support.
0chain/gosdk pull request #407
Opened 2022-03-05 08:44 UTC by princeparmar

Signed-off-by: Pradip Parmar <pradip@alfa-creator.com>

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-06 00:48 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-07 23:19 UTC, cnlangzi requested changes

2022-03-07 23:19 UTC, cnlangzi commented on zboxcore/sdk/deleteworker.go
> +	req.consensus = float32(initConsensus)
it is not good, breaks consensus. i think it should be better to update it with
```
req.consensus = float32(numList)
for i:=0;i<totalRefFound;i++ {
    req.consensus++
}
```

2022-03-07 23:19 UTC, cnlangzi commented on zboxcore/sdk/deleteworker.go
>  			refEntity, err := req.getObjectTreeFromBlobber(req.blobbers[blobberIdx])
could you use a predefined error variable instead of strings.Contains? 204/404/500 should be returned from blobber server now, right?  check https://wiki.crdb.io/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines#Error-handling or or the code I changed on your deletion PR about gorm.ErrRecordNotFound and io.ErrNotExists

2022-03-08 00:23 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-08 01:30 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-08 03:11 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-08 14:46 UTC, princeparmar commented on zboxcore/sdk/deleteworker.go
> +	req.consensus = float32(initConsensus)
actaully this is initial value we are using for consensus. same way we were initializing zero.

2022-03-28 02:54 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-02 19:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/406-partial-delete-support  |
| gosdk  | feature/406-partial-delete-support  |
| zboxcli  | feature/406-partial-delete-support  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/406-partial-delete-support  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-04-10 02:33 UTC, cnlangzi commented
moved this PR to https://github.com/0chain/gosdk/pull/427

2022-04-10 02:33 UTC, closed without merging