Feat/integrate wmlock on file operations
0chain/gosdk pull request #408
Opened 2022-03-07 00:48 UTC by cnlangzi

### Changes
- integrated `WriteLock` on `delete` command
- integrated `WriteLock` on `copy` command
- integrated `WriteLock` on `rename` command
- integrated `WriteLock` on `move` command 

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-07 03:47 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/integrate_wmlock_on_file_operations  |
| zboxcli  | feat/integrate_wmlock_on_file_operations  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-07 23:50 UTC, peterlimg requested changes

2022-03-07 23:50 UTC, peterlimg commented on zboxcore/sdk/copyworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
Delete failed -> Copy failed

2022-03-07 23:50 UTC, peterlimg commented on zboxcore/sdk/copyworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
Delete failed -> Copy failed

2022-03-07 23:50 UTC, peterlimg commented on zboxcore/sdk/renameworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
Delete failed -> Rename failed

2022-03-07 23:50 UTC, peterlimg commented on zboxcore/sdk/renameworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
Delete failed -> Rename failed

2022-03-08 00:25 UTC, cnlangzi commented on zboxcore/sdk/renameworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
fixed

2022-03-08 00:25 UTC, cnlangzi commented on zboxcore/sdk/renameworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
fixed

2022-03-08 00:25 UTC, cnlangzi commented on zboxcore/sdk/copyworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
fixed

2022-03-08 00:25 UTC, cnlangzi commented on zboxcore/sdk/copyworker.go
> +		return fmt.Errorf("Delete failed: %s", err.Error())
fixed

2022-03-08 06:26 UTC, peterlimg approved these changes
lgtm

2022-03-08 11:22 UTC, merged