Feat/available after
0chain/gosdk pull request #418
Opened 2022-03-21 04:04 UTC by cnlangzi

### Changes
-

### Fixes
- fixed issues on https://github.com/0chain/gosdk/pull/331

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-22 10:44 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/available_after  |
| zboxcli  | feat/available_after  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/available_after  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-23 12:42 UTC, peterlimg requested changes

2022-03-23 12:42 UTC, peterlimg commented on core/common/time.go
> +var ErrInvalidTime = errors.New("Invalid time")
Use lower case for error messages

2022-03-23 12:42 UTC, peterlimg commented on wasmsdk/blobber.go
> +		}
The `else` is unnecessary

2022-03-23 13:21 UTC, cnlangzi commented on wasmsdk/blobber.go
> +		}
fixed

2022-03-23 13:23 UTC, cnlangzi commented on core/common/time.go
> +var ErrInvalidTime = errors.New("Invalid time")
fixed

2022-03-23 14:33 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feat/available_after  |
| zboxcli  | feat/available_after  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feat/available_after  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-23 22:32 UTC, peterlimg approved these changes
lgtm

2022-03-24 03:34 UTC, merged