Fix/currency api
0chain/gosdk pull request #476
Opened 2022-06-03 03:40 UTC by cnlangzi

### Changes
-

### Fixes
- fixed https://github.com/0chain/gosdk/issues/463

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- zwalletcli:
- gosdk:

2022-06-03 12:01 UTC, peterlimg requested changes

2022-06-03 12:01 UTC, peterlimg commented on core/token/quote.go
> +		log.Println("token: ", err)
Please do not log error in gosdk

2022-06-03 12:01 UTC, peterlimg commented on core/token/quote.go
> +	GetUSDRate(ctx context.Context, symbol string) (float64, error)
Make the interface and method private, they will only be used in this package

2022-06-03 12:01 UTC, peterlimg commented on core/token/quote.go
> +package token
token is a good name, so please do not use it for this exchange rate query package. So perhaps rename to tokenrate.

Also, please rename file name to tokenrate.go, remove the prefix 'quote_' from the other 2 go files.

2022-06-03 12:01 UTC, peterlimg commented on core/token/quote.go
> +func GetTokenUSDRate(ctx context.Context, symbol string) (float64, error) {
Rename to GetUSD() to reduce naming repeating, so for package user, this will be tokenrate.GetUSD()

2022-06-06 01:38 UTC, cnlangzi commented on core/token/quote.go
> +		log.Println("token: ", err)
fixed

2022-06-06 01:38 UTC, cnlangzi commented on core/token/quote.go
> +	GetUSDRate(ctx context.Context, symbol string) (float64, error)
fixed

2022-06-06 01:38 UTC, cnlangzi commented on core/token/quote.go
> +package token
fixed

2022-06-06 01:38 UTC, cnlangzi commented on core/token/quote.go
> +func GetTokenUSDRate(ctx context.Context, symbol string) (float64, error) {
fixed

2022-06-06 02:32 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/currency_api  |
| zboxcli  | staging  |
| zwalletcli  | fix/currency_api  |
| 0chain  | staging  |
| blobber  | fix/currency_api  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-06-06 10:43 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/currency_api  |
| zboxcli  | staging  |
| zwalletcli  | fix/currency_api  |
| 0chain  | staging  |
| blobber  | fix/currency_api  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-06-07 12:27 UTC, peterlimg requested changes

2022-06-07 12:27 UTC, peterlimg commented on core/tokenrate/quote.go
> +
rename the quote.go to tokenrate.go

2022-06-08 00:23 UTC, cnlangzi commented on core/tokenrate/quote.go
> +
fixed

2022-06-08 03:15 UTC, peterlimg approved these changes
lgtm

2022-06-08 23:22 UTC, merged