Removed ID(), added ClientID(), added clientID parameter to nonce,
0chain/gosdk pull request #505
Opened 2022-07-03 10:45 UTC by Dmdv

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-07-25 12:04 UTC, dabasov requested changes

2022-07-25 12:04 UTC, dabasov commented on zcnbridge/example/main.go
> -//go:build ignore
do we need to build this?

2022-07-26 04:45 UTC, Dmdv commented on zcnbridge/example/main.go
> -//go:build ignore
Added build constraints

2022-07-26 07:30 UTC, Dmdv commented on zcnbridge/example/main.go
> -//go:build ignore
Done

2022-07-26 09:31 UTC, dabasov approved these changes
lgtm

2022-07-26 09:56 UTC, dabasov reviewed
lgtm

2022-07-26 10:36 UTC, merged