Feature/list recent files
0chain/gosdk pull request #532
Opened 2022-08-09 13:30 UTC by lpoli

### Changes
This PR will add feature to list recently added refs in paginated fashion.

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/755
- 0chain:
- system_test: https://github.com/0chain/system_test/pull/369
- zboxcli:
- zwalletcli:
- Other: ...

2022-08-10 04:07 UTC, peterlimg requested changes

2022-08-10 04:07 UTC, peterlimg commented on zboxcore/sdk/allocation.go
> +	offset := int64(page-1) * int64(pageLimit)
Validate the `page-1` and `pageLimit` value, they should both >= 0

2022-08-10 04:07 UTC, peterlimg commented on zboxcore/zboxutil/http.go
> +	params.Add("from_date", strconv.FormatInt(fromDate, 10))
Let's unify the param format, so `from-date` and `page-limit`, or just `limit` for the page size perhaps.

2022-08-11 03:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | feature/recent-refs  |
| gosdk  | feature/list-recent-files  |
| zboxcli  | feature/list-recent-files  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-08-11 11:59 UTC, peterlimg approved these changes
lgtm

2022-08-15 00:26 UTC, merged