[WIP] Add delete authorizer method
0chain/gosdk pull request #564
Opened 2022-09-04 13:27 UTC by uneet7

### Changes
- PR adds the delete authorizer method to call 0Chain's `delete-authorizer` ZCN smart contract

### Fixes
- https://github.com/0chain/0chain/issues/1625

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-09-11 20:08 UTC, dabasov requested changes

2022-09-11 20:08 UTC, dabasov commented on zcncore/transaction.go
> +type DeleteAuthorizerPayload struct {
we want to send authorizer id here

2022-09-27 13:04 UTC, peterlimg approved these changes
lgtm

2022-09-28 18:58 UTC, dabasov approved these changes
lgtm

2022-09-28 20:28 UTC, merged