Fix/improved wasm perf
0chain/gosdk pull request #591
Opened 2022-09-30 06:18 UTC by cnlangzi

### Changes
- wasm: added cache for sign to reduce js calls in blobber requests
- wasm: implement sleep  in wasm with channel instead of setTimeout in js. it reduces communication between zcn.wasm and js

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-10-01 05:42 UTC, peterlimg requested changes

2022-10-01 05:42 UTC, peterlimg commented on wasmsdk/proxy.go
> +			// jsSleep := jsProxy.Get("sleep")
Clean up the commented code

2022-10-02 01:32 UTC, cnlangzi commented on wasmsdk/proxy.go
> +			// jsSleep := jsProxy.Get("sleep")
fixed

2022-10-02 06:45 UTC, peterlimg approved these changes
lgtm

2022-10-02 12:30 UTC, merged