Atomic/move
0chain/gosdk pull request #627
Opened 2022-11-01 07:11 UTC by lpoli

### Changes
This PR had made move operation atomic. Previously it would be copy + delete in which client was charged for copy operation.

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber: https://github.com/0chain/blobber/pull/866
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-11-01 17:28 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | atomic/move  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | atomic/move  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-03 18:41 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | atomic/move  |
| zboxcli  | atomic/move  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | atomic/move  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-04 05:32 UTC, peterlimg requested changes

2022-11-04 05:32 UTC, peterlimg commented on zboxcore/allocationchange/moveobject.go
> +		return errors.New("file_not_found", "Object to m9ve not found in blobber")
m9ve -> move

2022-11-04 05:32 UTC, peterlimg commented on zboxcore/sdk/moveworker.go
> +		go func(blobberIdx int) {
call  defer wg.Done()  here instead of  passing it to the moveBlobberObject

2022-11-04 09:40 UTC, peterlimg approved these changes
lgtm

2022-11-04 11:33 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | atomic/move  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | atomic/move  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-04 17:33 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | atomic/move  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-11-04 17:36 UTC, merged