Fix: modified mintWZCN to return payload
0chain/gosdk pull request #638
Opened 2022-11-07 20:04 UTC by YarikRevich

#Refers to issue #635

2022-11-09 06:12 UTC, peterlimg requested changes, later dismissed

2022-11-09 06:12 UTC, peterlimg commented on zcnbridge/bridge.go
> +	bridgeInstance, transactOpts, err := b.prepareBridge(ctx, "burn", amount, b.ClientID())
Please use the same data type of ClientID for gas estimation and Brun. Seems the previous code was correct.

2022-11-09 06:12 UTC, peterlimg commented on zcnbridge/bridge.go
> +	//return nil, nil
Remove unused code and adjust the comments below

2022-11-17 07:17 UTC, cnlangzi approved these changes
LGTM

2022-11-21 20:34 UTC, dabasov approved these changes
lgtm

2022-11-21 20:34 UTC, merged