Fix: bridge "burnZCN" in wasm
0chain/gosdk pull request #679
Opened 2022-12-06 13:14 UTC by YarikRevich

2022-12-06 13:30 UTC, dabasov requested changes

2022-12-06 13:30 UTC, dabasov commented on wasmsdk/bridge.go
> +	err = tx.Verify(context.Background())
I think we should verify inside `bridge.BurnZCN`

2022-12-06 13:38 UTC, dabasov approved these changes
lgtm

2022-12-07 15:50 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | YES  |
| system-tests  | master  |
| gosdk  | fix/bridge_burn_zcn_wasm  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-12-07 16:35 UTC, merged