install make command
0chain/gosdk pull request #716
Opened 2023-01-13 06:50 UTC by Manali-Jain-squareops

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-01-13 07:12 UTC, cnlangzi approved these changes
LGTM

2023-01-13 07:14 UTC, cnlangzi requested changes, later dismissed

2023-01-13 07:14 UTC, cnlangzi commented on .github/workflows/build-sdks.yml
> +        run: sudo apt update && sudo apt upgrade && sudo apt install build-essential -y
```suggestion
run: sudo apt update -y && sudo apt upgrade -y && sudo apt install build-essential -y
```

2023-01-13 07:14 UTC, cnlangzi commented on .github/workflows/build-sdks.yml
> +        run: sudo apt update && sudo apt upgrade && sudo apt install build-essential -y
```suggestion
run: sudo apt update -y && sudo apt upgrade -y && sudo apt install build-essential -y
```

2023-01-13 07:14 UTC, cnlangzi commented on .github/workflows/tests.yml
> +        run: sudo apt update && sudo apt upgrade && sudo apt install build-essential -y
```suggestion
run: sudo apt update -y && sudo apt upgrade -y && sudo apt install build-essential -y
```

2023-01-13 07:14 UTC, cnlangzi commented on .github/workflows/tests.yml
> +        run: sudo apt update && sudo apt upgrade && sudo apt install build-essential -y
```suggestion
run: sudo apt update -y && sudo apt upgrade -y && sudo apt install build-essential -y
```

2023-01-14 21:24 UTC, peterlimg approved these changes
lgtm

2023-01-14 21:25 UTC, merged

2023-01-15 02:47 UTC, cnlangzi commented
@peterlimg  the fix doesn't work.

2023-01-16 09:01 UTC, cnlangzi commented
fixed it on https://github.com/0chain/gosdk/pull/722