Remove sending custom timeout as an option to resty object
0chain/gosdk pull request #758
Opened 2023-02-08 04:17 UTC by aniketsingh03

### Changes
This PR removes the custom timeout param that was being sent while creating resty object. The timeout will now be controlled by the API caller/client through the request context. However, a default timeout of 10s (DefaultRequestTimeout) is still there for requests which do not have any timeout set.

### Fixes
Fixes #737 

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-02-09 05:10 UTC, aniketsingh03 commented
Can you guys review this @dabasov @cnlangzi @peterlimg?

2023-02-10 11:36 UTC, peterlimg requested changes, later dismissed

2023-02-10 11:36 UTC, peterlimg commented on zcncore/transaction_query_base.go
> +	}()
We don't need this goroutine, call `defer cancel()` would be fine.

2023-02-10 17:12 UTC, aniketsingh03 commented on zcncore/transaction_query_base.go
> +	}()
Done

2023-02-11 21:00 UTC, dabasov reviewed
lgtm

2023-02-11 21:00 UTC, dabasov approved these changes
lgtm

2023-02-11 21:01 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | improve-resty-package  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-11 21:01 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | true  |
| system-tests  | master  |
| gosdk  | improve-resty-package  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-11 21:21 UTC, merged

2023-02-12 03:55 UTC, aniketsingh03 commented
Thanks!