Improve the rounding off logic in Balance class
0chain/gosdk pull request #794
Opened 2023-02-22 14:51 UTC by aniketsingh03

### Changes
- This PR improves the logic in `misc.go` for improved rounding off when converting floats to ints 

### Fixes
- #752 

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-02-23 08:36 UTC, peterlimg requested changes

2023-02-23 08:36 UTC, peterlimg commented on core/common/misc.go
> +	ErrUint64AddOverflow = errors.New("", "uint64 addition overflow")
Let's use standard errors package, so `errors.New("uint64 addition overflow")`, so as the other errors above.

2023-02-23 13:20 UTC, dabasov approved these changes
lgtm

2023-02-23 20:41 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix-rounding-off-for-balance  |
| zboxcli  | fix-rounding-off-for-balance  |
| zwalletcli  | fix-rounding-off-for-balance  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-02-26 00:01 UTC, peterlimg approved these changes
LGTM

2023-03-01 01:12 UTC, cnlangzi approved these changes
LGTM

2023-03-01 06:51 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | fix-rounding-off-for-balance  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-01 06:53 UTC, merged