fix(path): replaced filepath methodes with common/path for remotepath
0chain/gosdk pull request #852
Opened 2023-03-17 10:44 UTC by cnlangzi

### Changes
-

### Fixes
- fixed filepath issue on --remotepath. filepath.Join/filepath.Split/filepath.Dir/filepath.Clean are replaced with common's

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-03-17 12:44 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/filepath_issues  |
| zboxcli  | fix/filepath_issues  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-18 12:59 UTC, peterlimg requested changes

2023-03-18 12:59 UTC, peterlimg commented on core/pathutil/path.go
> +	return "/" + strings.Join(items, "/")
We'd better use relative path. User can call `Joins("/", "the path")` to get absolute path.

2023-03-20 07:34 UTC, peterlimg approved these changes
LGTM

2023-03-24 03:04 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/filepath_issues  |
| zboxcli  | fix/filepath_issues  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-24 08:54 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | fix/filepath_issues  |
| zboxcli  | fix/filepath_issues  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2023-03-24 08:56 UTC, merged