[WIP] Optimize download/upload processes
0chain/gosdk pull request #878
Opened 2023-03-31 18:11 UTC by din-mukhammed

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-04-21 03:16 UTC, lpoli requested changes, later dismissed
Download is not optimized at all. We should also use readcounter quota system as @dabasov suggested. Also the blockdownloadworker.go should be changed as it makes download request sequential with the use of channel.

For upload I think @Roshan-Mehta 's work will optimize it but please also check for bath upload feature to increase upload size and use it in loadtest.

2023-04-21 03:16 UTC, lpoli commented on zboxcore/sdk/downloadworker.go
>  		if req.isDownloadCanceled {
This condition should be checked in above block

2023-04-28 13:59 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-01 18:26 UTC, dabasov approved these changes
lgtm

2023-05-08 17:48 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-12 10:21 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | pr-1047-f1029ad3  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-12 10:22 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | pr-1047  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-15 19:41 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-15 20:11 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-21 14:17 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-23 08:41 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | optimize-download-fix  |
| gosdk  | optimize-download-upload  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | 878-optimize-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-23 10:36 UTC, merged