Fix: subgraph initialization
0chain/gosdk pull request #904
Opened 2023-04-16 17:47 UTC by YarikRevich

2023-04-17 16:49 UTC, dabasov requested changes

2023-04-17 16:49 UTC, dabasov commented on zcnbridge/bridge.go
> +	graphQlClient, err := b.CreateSubgraphClient()
please do not expose graphql to clients and move this service to authorizers

2023-04-20 13:56 UTC, dabasov approved these changes
lgtm

2023-04-20 15:58 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | feature/graphql_switch  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-20 16:06 UTC, merged