expose wasm: updateAllocationWithRepair
0chain/gosdk pull request #908
Opened 2023-04-20 00:38 UTC by boddumanohar

### Changes
- exposes a function to updateAllocationWithRepair

### Fixes
- 

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test: https://github.com/0chain/system_test/pull/633
- zboxcli: https://github.com/0chain/zboxcli/pull/401
- zwalletcli:
- Other: ...

2023-04-21 03:57 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add-replace-blobber  |
| gosdk  | update-alloc  |
| zboxcli  | add-replace-blobber  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-04-22 21:50 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | add-replace-blobber  |
| gosdk  | update-alloc  |
| zboxcli  | add-replace-blobber  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-16 20:23 UTC, boddumanohar commented on zboxcore/sdk/downloadworker.go
> +func GetFileRefFromBlobber(allocationID, blobberId, remotePath string) (fRef *fileref.FileRef, err error) {
I am using this function in system_tests.

2023-05-31 05:04 UTC, peterlimg requested changes

2023-05-31 05:04 UTC, peterlimg commented on zboxcore/sdk/downloadworker.go
> +	return resp.fileref, nil
Let's return `resp.fileref, resp.err` as mentioned in another PR

2023-05-31 05:17 UTC, peterlimg approved these changes
LGTM

2023-06-05 04:50 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | add-replace-blobber  |
| gosdk  | update-alloc  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | staging  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-06 10:09 UTC, merged