Two phase timestamp
0chain/gosdk pull request #938
Opened 2023-05-02 12:16 UTC by Hitenjain14

### Changes
-

### Fixes
-

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/gosdk/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- blobber:
- 0chain:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-05-18 04:55 UTC, lpoli requested changes

2023-05-18 04:55 UTC, lpoli commented on zboxcore/sdk/commitworker.go
> +		if lR.LatestWM.ClientID != client.GetClientID() {
This check seems useful for debug purpose only.
Signature verification will also prove if client id is same or not

2023-05-18 04:55 UTC, lpoli commented on zboxcore/fileref/fileref.go
> +	return fmt.Sprintf("%s:%s", r.AllocationID, r.Path)
Lets also include fileID in hash calculation for directory.

2023-05-18 14:26 UTC, dabasov approved these changes
lgtm

2023-05-18 15:35 UTC, lpoli approved these changes

2023-05-21 13:46 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/create-dir  |
| gosdk  | two-phase-timestamp  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-26 10:13 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | two-phase-timestamp  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | test-createdir  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-26 13:36 UTC, merged